// Code generated by usestdlibvars, DO NOT EDIT.

package time_test

var (
	_ = "time.Date(2023, 1, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 1, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.January, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 10, 2, 3, 4, 5, 0, time.UTC)" // want `"time\.Date\(2023, 10, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.October, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 11, 2, 3, 4, 5, 0, time.UTC)" // want `"time\.Date\(2023, 11, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.November, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 12, 2, 3, 4, 5, 0, time.UTC)" // want `"time\.Date\(2023, 12, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.December, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 2, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 2, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.February, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 3, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 3, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.March, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 4, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 4, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.April, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 5, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 5, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.May, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 6, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 6, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.June, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 7, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 7, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.July, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 8, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 8, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.August, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 9, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 9, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.September, 2, 3, 4, 5, 0, time\.UTC\)`
)

const (
	_ = "time.Date(2023, 1, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 1, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.January, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 10, 2, 3, 4, 5, 0, time.UTC)" // want `"time\.Date\(2023, 10, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.October, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 11, 2, 3, 4, 5, 0, time.UTC)" // want `"time\.Date\(2023, 11, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.November, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 12, 2, 3, 4, 5, 0, time.UTC)" // want `"time\.Date\(2023, 12, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.December, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 2, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 2, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.February, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 3, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 3, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.March, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 4, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 4, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.April, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 5, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 5, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.May, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 6, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 6, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.June, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 7, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 7, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.July, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 8, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 8, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.August, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = "time.Date(2023, 9, 2, 3, 4, 5, 0, time.UTC)"  // want `"time\.Date\(2023, 9, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.September, 2, 3, 4, 5, 0, time\.UTC\)`
)

var (
	_ = func(s string) string { return s }("time.Date(2023, 1, 2, 3, 4, 5, 0, time.UTC)")  // want `"time\.Date\(2023, 1, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.January, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 10, 2, 3, 4, 5, 0, time.UTC)") // want `"time\.Date\(2023, 10, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.October, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 11, 2, 3, 4, 5, 0, time.UTC)") // want `"time\.Date\(2023, 11, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.November, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 12, 2, 3, 4, 5, 0, time.UTC)") // want `"time\.Date\(2023, 12, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.December, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 2, 2, 3, 4, 5, 0, time.UTC)")  // want `"time\.Date\(2023, 2, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.February, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 3, 2, 3, 4, 5, 0, time.UTC)")  // want `"time\.Date\(2023, 3, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.March, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 4, 2, 3, 4, 5, 0, time.UTC)")  // want `"time\.Date\(2023, 4, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.April, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 5, 2, 3, 4, 5, 0, time.UTC)")  // want `"time\.Date\(2023, 5, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.May, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 6, 2, 3, 4, 5, 0, time.UTC)")  // want `"time\.Date\(2023, 6, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.June, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 7, 2, 3, 4, 5, 0, time.UTC)")  // want `"time\.Date\(2023, 7, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.July, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 8, 2, 3, 4, 5, 0, time.UTC)")  // want `"time\.Date\(2023, 8, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.August, 2, 3, 4, 5, 0, time\.UTC\)`
	_ = func(s string) string { return s }("time.Date(2023, 9, 2, 3, 4, 5, 0, time.UTC)")  // want `"time\.Date\(2023, 9, 2, 3, 4, 5, 0, time\.UTC\)" can be replaced by time\.Date\(2023, time\.September, 2, 3, 4, 5, 0, time\.UTC\)`
)
