// Code generated by usestdlibvars, DO NOT EDIT.

package time_test

import "time"

func _() {
	var _ = time.Date(2023, 1, 2, 3, 4, 5, 0, time.UTC)  // want `"1" can be replaced by time\.January`
	var _ = time.Date(2023, 10, 2, 3, 4, 5, 0, time.UTC) // want `"10" can be replaced by time\.October`
	var _ = time.Date(2023, 11, 2, 3, 4, 5, 0, time.UTC) // want `"11" can be replaced by time\.November`
	var _ = time.Date(2023, 12, 2, 3, 4, 5, 0, time.UTC) // want `"12" can be replaced by time\.December`
	var _ = time.Date(2023, 2, 2, 3, 4, 5, 0, time.UTC)  // want `"2" can be replaced by time\.February`
	var _ = time.Date(2023, 3, 2, 3, 4, 5, 0, time.UTC)  // want `"3" can be replaced by time\.March`
	var _ = time.Date(2023, 4, 2, 3, 4, 5, 0, time.UTC)  // want `"4" can be replaced by time\.April`
	var _ = time.Date(2023, 5, 2, 3, 4, 5, 0, time.UTC)  // want `"5" can be replaced by time\.May`
	var _ = time.Date(2023, 6, 2, 3, 4, 5, 0, time.UTC)  // want `"6" can be replaced by time\.June`
	var _ = time.Date(2023, 7, 2, 3, 4, 5, 0, time.UTC)  // want `"7" can be replaced by time\.July`
	var _ = time.Date(2023, 8, 2, 3, 4, 5, 0, time.UTC)  // want `"8" can be replaced by time\.August`
	var _ = time.Date(2023, 9, 2, 3, 4, 5, 0, time.UTC)  // want `"9" can be replaced by time\.September`

	var _ = time.Date(2023, time.January, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.October, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.November, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.December, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.February, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.March, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.April, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.May, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.June, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.July, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.August, 2, 3, 4, 5, 0, time.UTC)
	var _ = time.Date(2023, time.September, 2, 3, 4, 5, 0, time.UTC)
}

var _ = time.Date(2023, 13, 2, 3, 4, 5, 0, time.UTC)
