// Code generated by usestdlibvars, DO NOT EDIT.

package time_test

var (
	_ = "01/02 03:04:05PM '06 -0700"          // want `"01/02 03:04:05PM '06 -0700" can be replaced by time\.Layout`
	_ = "02 Jan 06 15:04 -0700"               // want `"02 Jan 06 15:04 -0700" can be replaced by time\.RFC822Z`
	_ = "02 Jan 06 15:04 MST"                 // want `"02 Jan 06 15:04 MST" can be replaced by time\.RFC822`
	_ = "15:04:05"                            // want `"15:04:05" can be replaced by time\.TimeOnly`
	_ = "2006-01-02"                          // want `"2006-01-02" can be replaced by time\.DateOnly`
	_ = "2006-01-02 15:04:05"                 // want `"2006-01-02 15:04:05" can be replaced by time\.DateTime`
	_ = "2006-01-02T15:04:05.999999999Z07:00" // want `"2006-01-02T15:04:05\.999999999Z07:00" can be replaced by time\.RFC3339Nano`
	_ = "2006-01-02T15:04:05Z07:00"           // want `"2006-01-02T15:04:05Z07:00" can be replaced by time\.RFC3339`
	_ = "3:04PM"                              // want `"3:04PM" can be replaced by time\.Kitchen`
	_ = "Jan _2 15:04:05"                     // want `"Jan _2 15:04:05" can be replaced by time\.Stamp`
	_ = "Jan _2 15:04:05.000"                 // want `"Jan _2 15:04:05\.000" can be replaced by time\.StampMilli`
	_ = "Jan _2 15:04:05.000000"              // want `"Jan _2 15:04:05\.000000" can be replaced by time\.StampMicro`
	_ = "Jan _2 15:04:05.000000000"           // want `"Jan _2 15:04:05\.000000000" can be replaced by time\.StampNano`
	_ = "Mon Jan 02 15:04:05 -0700 2006"      // want `"Mon Jan 02 15:04:05 -0700 2006" can be replaced by time\.RubyDate`
	_ = "Mon Jan _2 15:04:05 2006"            // want `"Mon Jan _2 15:04:05 2006" can be replaced by time\.ANSIC`
	_ = "Mon Jan _2 15:04:05 MST 2006"        // want `"Mon Jan _2 15:04:05 MST 2006" can be replaced by time\.UnixDate`
	_ = "Mon, 02 Jan 2006 15:04:05 -0700"     // want `"Mon, 02 Jan 2006 15:04:05 -0700" can be replaced by time\.RFC1123Z`
	_ = "Mon, 02 Jan 2006 15:04:05 MST"       // want `"Mon, 02 Jan 2006 15:04:05 MST" can be replaced by time\.RFC1123`
	_ = "Monday, 02-Jan-06 15:04:05 MST"      // want `"Monday, 02-Jan-06 15:04:05 MST" can be replaced by time\.RFC850`
)

const (
	_ = "01/02 03:04:05PM '06 -0700"          // want `"01/02 03:04:05PM '06 -0700" can be replaced by time\.Layout`
	_ = "02 Jan 06 15:04 -0700"               // want `"02 Jan 06 15:04 -0700" can be replaced by time\.RFC822Z`
	_ = "02 Jan 06 15:04 MST"                 // want `"02 Jan 06 15:04 MST" can be replaced by time\.RFC822`
	_ = "15:04:05"                            // want `"15:04:05" can be replaced by time\.TimeOnly`
	_ = "2006-01-02"                          // want `"2006-01-02" can be replaced by time\.DateOnly`
	_ = "2006-01-02 15:04:05"                 // want `"2006-01-02 15:04:05" can be replaced by time\.DateTime`
	_ = "2006-01-02T15:04:05.999999999Z07:00" // want `"2006-01-02T15:04:05\.999999999Z07:00" can be replaced by time\.RFC3339Nano`
	_ = "2006-01-02T15:04:05Z07:00"           // want `"2006-01-02T15:04:05Z07:00" can be replaced by time\.RFC3339`
	_ = "3:04PM"                              // want `"3:04PM" can be replaced by time\.Kitchen`
	_ = "Jan _2 15:04:05"                     // want `"Jan _2 15:04:05" can be replaced by time\.Stamp`
	_ = "Jan _2 15:04:05.000"                 // want `"Jan _2 15:04:05\.000" can be replaced by time\.StampMilli`
	_ = "Jan _2 15:04:05.000000"              // want `"Jan _2 15:04:05\.000000" can be replaced by time\.StampMicro`
	_ = "Jan _2 15:04:05.000000000"           // want `"Jan _2 15:04:05\.000000000" can be replaced by time\.StampNano`
	_ = "Mon Jan 02 15:04:05 -0700 2006"      // want `"Mon Jan 02 15:04:05 -0700 2006" can be replaced by time\.RubyDate`
	_ = "Mon Jan _2 15:04:05 2006"            // want `"Mon Jan _2 15:04:05 2006" can be replaced by time\.ANSIC`
	_ = "Mon Jan _2 15:04:05 MST 2006"        // want `"Mon Jan _2 15:04:05 MST 2006" can be replaced by time\.UnixDate`
	_ = "Mon, 02 Jan 2006 15:04:05 -0700"     // want `"Mon, 02 Jan 2006 15:04:05 -0700" can be replaced by time\.RFC1123Z`
	_ = "Mon, 02 Jan 2006 15:04:05 MST"       // want `"Mon, 02 Jan 2006 15:04:05 MST" can be replaced by time\.RFC1123`
	_ = "Monday, 02-Jan-06 15:04:05 MST"      // want `"Monday, 02-Jan-06 15:04:05 MST" can be replaced by time\.RFC850`
)

var (
	_ = func(s string) string { return s }("01/02 03:04:05PM '06 -0700")          // want `"01/02 03:04:05PM '06 -0700" can be replaced by time\.Layout`
	_ = func(s string) string { return s }("02 Jan 06 15:04 -0700")               // want `"02 Jan 06 15:04 -0700" can be replaced by time\.RFC822Z`
	_ = func(s string) string { return s }("02 Jan 06 15:04 MST")                 // want `"02 Jan 06 15:04 MST" can be replaced by time\.RFC822`
	_ = func(s string) string { return s }("15:04:05")                            // want `"15:04:05" can be replaced by time\.TimeOnly`
	_ = func(s string) string { return s }("2006-01-02")                          // want `"2006-01-02" can be replaced by time\.DateOnly`
	_ = func(s string) string { return s }("2006-01-02 15:04:05")                 // want `"2006-01-02 15:04:05" can be replaced by time\.DateTime`
	_ = func(s string) string { return s }("2006-01-02T15:04:05.999999999Z07:00") // want `"2006-01-02T15:04:05\.999999999Z07:00" can be replaced by time\.RFC3339Nano`
	_ = func(s string) string { return s }("2006-01-02T15:04:05Z07:00")           // want `"2006-01-02T15:04:05Z07:00" can be replaced by time\.RFC3339`
	_ = func(s string) string { return s }("3:04PM")                              // want `"3:04PM" can be replaced by time\.Kitchen`
	_ = func(s string) string { return s }("Jan _2 15:04:05")                     // want `"Jan _2 15:04:05" can be replaced by time\.Stamp`
	_ = func(s string) string { return s }("Jan _2 15:04:05.000")                 // want `"Jan _2 15:04:05\.000" can be replaced by time\.StampMilli`
	_ = func(s string) string { return s }("Jan _2 15:04:05.000000")              // want `"Jan _2 15:04:05\.000000" can be replaced by time\.StampMicro`
	_ = func(s string) string { return s }("Jan _2 15:04:05.000000000")           // want `"Jan _2 15:04:05\.000000000" can be replaced by time\.StampNano`
	_ = func(s string) string { return s }("Mon Jan 02 15:04:05 -0700 2006")      // want `"Mon Jan 02 15:04:05 -0700 2006" can be replaced by time\.RubyDate`
	_ = func(s string) string { return s }("Mon Jan _2 15:04:05 2006")            // want `"Mon Jan _2 15:04:05 2006" can be replaced by time\.ANSIC`
	_ = func(s string) string { return s }("Mon Jan _2 15:04:05 MST 2006")        // want `"Mon Jan _2 15:04:05 MST 2006" can be replaced by time\.UnixDate`
	_ = func(s string) string { return s }("Mon, 02 Jan 2006 15:04:05 -0700")     // want `"Mon, 02 Jan 2006 15:04:05 -0700" can be replaced by time\.RFC1123Z`
	_ = func(s string) string { return s }("Mon, 02 Jan 2006 15:04:05 MST")       // want `"Mon, 02 Jan 2006 15:04:05 MST" can be replaced by time\.RFC1123`
	_ = func(s string) string { return s }("Monday, 02-Jan-06 15:04:05 MST")      // want `"Monday, 02-Jan-06 15:04:05 MST" can be replaced by time\.RFC850`
)
