// Code generated by usestdlibvars, DO NOT EDIT.

package time_test

var (
	_ = "April"     // want `"April" can be replaced by time\.April\.String\(\)`
	_ = "August"    // want `"August" can be replaced by time\.August\.String\(\)`
	_ = "December"  // want `"December" can be replaced by time\.December\.String\(\)`
	_ = "February"  // want `"February" can be replaced by time\.February\.String\(\)`
	_ = "January"   // want `"January" can be replaced by time\.January\.String\(\)`
	_ = "July"      // want `"July" can be replaced by time\.July\.String\(\)`
	_ = "June"      // want `"June" can be replaced by time\.June\.String\(\)`
	_ = "March"     // want `"March" can be replaced by time\.March\.String\(\)`
	_ = "May"       // want `"May" can be replaced by time\.May\.String\(\)`
	_ = "November"  // want `"November" can be replaced by time\.November\.String\(\)`
	_ = "October"   // want `"October" can be replaced by time\.October\.String\(\)`
	_ = "September" // want `"September" can be replaced by time\.September\.String\(\)`
)

const (
	_ = "April"     // want `"April" can be replaced by time\.April\.String\(\)`
	_ = "August"    // want `"August" can be replaced by time\.August\.String\(\)`
	_ = "December"  // want `"December" can be replaced by time\.December\.String\(\)`
	_ = "February"  // want `"February" can be replaced by time\.February\.String\(\)`
	_ = "January"   // want `"January" can be replaced by time\.January\.String\(\)`
	_ = "July"      // want `"July" can be replaced by time\.July\.String\(\)`
	_ = "June"      // want `"June" can be replaced by time\.June\.String\(\)`
	_ = "March"     // want `"March" can be replaced by time\.March\.String\(\)`
	_ = "May"       // want `"May" can be replaced by time\.May\.String\(\)`
	_ = "November"  // want `"November" can be replaced by time\.November\.String\(\)`
	_ = "October"   // want `"October" can be replaced by time\.October\.String\(\)`
	_ = "September" // want `"September" can be replaced by time\.September\.String\(\)`
)

var (
	_ = func(s string) string { return s }("April")     // want `"April" can be replaced by time\.April\.String\(\)`
	_ = func(s string) string { return s }("August")    // want `"August" can be replaced by time\.August\.String\(\)`
	_ = func(s string) string { return s }("December")  // want `"December" can be replaced by time\.December\.String\(\)`
	_ = func(s string) string { return s }("February")  // want `"February" can be replaced by time\.February\.String\(\)`
	_ = func(s string) string { return s }("January")   // want `"January" can be replaced by time\.January\.String\(\)`
	_ = func(s string) string { return s }("July")      // want `"July" can be replaced by time\.July\.String\(\)`
	_ = func(s string) string { return s }("June")      // want `"June" can be replaced by time\.June\.String\(\)`
	_ = func(s string) string { return s }("March")     // want `"March" can be replaced by time\.March\.String\(\)`
	_ = func(s string) string { return s }("May")       // want `"May" can be replaced by time\.May\.String\(\)`
	_ = func(s string) string { return s }("November")  // want `"November" can be replaced by time\.November\.String\(\)`
	_ = func(s string) string { return s }("October")   // want `"October" can be replaced by time\.October\.String\(\)`
	_ = func(s string) string { return s }("September") // want `"September" can be replaced by time\.September\.String\(\)`
)
