// Code generated by usestdlibvars, DO NOT EDIT.

package time_test

var (
	_ = "Friday"    // want `"Friday" can be replaced by time\.Friday\.String\(\)`
	_ = "Monday"    // want `"Monday" can be replaced by time\.Monday\.String\(\)`
	_ = "Saturday"  // want `"Saturday" can be replaced by time\.Saturday\.String\(\)`
	_ = "Sunday"    // want `"Sunday" can be replaced by time\.Sunday\.String\(\)`
	_ = "Thursday"  // want `"Thursday" can be replaced by time\.Thursday\.String\(\)`
	_ = "Tuesday"   // want `"Tuesday" can be replaced by time\.Tuesday\.String\(\)`
	_ = "Wednesday" // want `"Wednesday" can be replaced by time\.Wednesday\.String\(\)`
)

const (
	_ = "Friday"    // want `"Friday" can be replaced by time\.Friday\.String\(\)`
	_ = "Monday"    // want `"Monday" can be replaced by time\.Monday\.String\(\)`
	_ = "Saturday"  // want `"Saturday" can be replaced by time\.Saturday\.String\(\)`
	_ = "Sunday"    // want `"Sunday" can be replaced by time\.Sunday\.String\(\)`
	_ = "Thursday"  // want `"Thursday" can be replaced by time\.Thursday\.String\(\)`
	_ = "Tuesday"   // want `"Tuesday" can be replaced by time\.Tuesday\.String\(\)`
	_ = "Wednesday" // want `"Wednesday" can be replaced by time\.Wednesday\.String\(\)`
)

var (
	_ = func(s string) string { return s }("Friday")    // want `"Friday" can be replaced by time\.Friday\.String\(\)`
	_ = func(s string) string { return s }("Monday")    // want `"Monday" can be replaced by time\.Monday\.String\(\)`
	_ = func(s string) string { return s }("Saturday")  // want `"Saturday" can be replaced by time\.Saturday\.String\(\)`
	_ = func(s string) string { return s }("Sunday")    // want `"Sunday" can be replaced by time\.Sunday\.String\(\)`
	_ = func(s string) string { return s }("Thursday")  // want `"Thursday" can be replaced by time\.Thursday\.String\(\)`
	_ = func(s string) string { return s }("Tuesday")   // want `"Tuesday" can be replaced by time\.Tuesday\.String\(\)`
	_ = func(s string) string { return s }("Wednesday") // want `"Wednesday" can be replaced by time\.Wednesday\.String\(\)`
)
