// Code generated by usestdlibvars, DO NOT EDIT.

package time_test

import "fmt"

var (
	_ = "Friday"    // want `"Friday" can be replaced by time\.Friday\.String\(\)`
	_ = "Monday"    // want `"Monday" can be replaced by time\.Monday\.String\(\)`
	_ = "Saturday"  // want `"Saturday" can be replaced by time\.Saturday\.String\(\)`
	_ = "Sunday"    // want `"Sunday" can be replaced by time\.Sunday\.String\(\)`
	_ = "Thursday"  // want `"Thursday" can be replaced by time\.Thursday\.String\(\)`
	_ = "Tuesday"   // want `"Tuesday" can be replaced by time\.Tuesday\.String\(\)`
	_ = "Wednesday" // want `"Wednesday" can be replaced by time\.Wednesday\.String\(\)`
)

const (
	_ = "Friday"    // want `"Friday" can be replaced by time\.Friday\.String\(\)`
	_ = "Monday"    // want `"Monday" can be replaced by time\.Monday\.String\(\)`
	_ = "Saturday"  // want `"Saturday" can be replaced by time\.Saturday\.String\(\)`
	_ = "Sunday"    // want `"Sunday" can be replaced by time\.Sunday\.String\(\)`
	_ = "Thursday"  // want `"Thursday" can be replaced by time\.Thursday\.String\(\)`
	_ = "Tuesday"   // want `"Tuesday" can be replaced by time\.Tuesday\.String\(\)`
	_ = "Wednesday" // want `"Wednesday" can be replaced by time\.Wednesday\.String\(\)`
)

func _() {
	_ = func(s string) string { return s }("Friday") // want `"Friday" can be replaced by time\.Friday\.String\(\)`
	_ = func(s string) string { return s }("text before key Friday")
	_ = func(s string) string { return s }("Friday text after key")
	_ = func(s string) string { return s }("Monday") // want `"Monday" can be replaced by time\.Monday\.String\(\)`
	_ = func(s string) string { return s }("text before key Monday")
	_ = func(s string) string { return s }("Monday text after key")
	_ = func(s string) string { return s }("Saturday") // want `"Saturday" can be replaced by time\.Saturday\.String\(\)`
	_ = func(s string) string { return s }("text before key Saturday")
	_ = func(s string) string { return s }("Saturday text after key")
	_ = func(s string) string { return s }("Sunday") // want `"Sunday" can be replaced by time\.Sunday\.String\(\)`
	_ = func(s string) string { return s }("text before key Sunday")
	_ = func(s string) string { return s }("Sunday text after key")
	_ = func(s string) string { return s }("Thursday") // want `"Thursday" can be replaced by time\.Thursday\.String\(\)`
	_ = func(s string) string { return s }("text before key Thursday")
	_ = func(s string) string { return s }("Thursday text after key")
	_ = func(s string) string { return s }("Tuesday") // want `"Tuesday" can be replaced by time\.Tuesday\.String\(\)`
	_ = func(s string) string { return s }("text before key Tuesday")
	_ = func(s string) string { return s }("Tuesday text after key")
	_ = func(s string) string { return s }("Wednesday") // want `"Wednesday" can be replaced by time\.Wednesday\.String\(\)`
	_ = func(s string) string { return s }("text before key Wednesday")
	_ = func(s string) string { return s }("Wednesday text after key")
}

func _() {
	_ = fmt.Sprint("Friday") // want `"Friday" can be replaced by time\.Friday\.String\(\)`
	_ = fmt.Sprint("text before key Friday")
	_ = fmt.Sprint("Friday text after key")
	_ = fmt.Sprint("Monday") // want `"Monday" can be replaced by time\.Monday\.String\(\)`
	_ = fmt.Sprint("text before key Monday")
	_ = fmt.Sprint("Monday text after key")
	_ = fmt.Sprint("Saturday") // want `"Saturday" can be replaced by time\.Saturday\.String\(\)`
	_ = fmt.Sprint("text before key Saturday")
	_ = fmt.Sprint("Saturday text after key")
	_ = fmt.Sprint("Sunday") // want `"Sunday" can be replaced by time\.Sunday\.String\(\)`
	_ = fmt.Sprint("text before key Sunday")
	_ = fmt.Sprint("Sunday text after key")
	_ = fmt.Sprint("Thursday") // want `"Thursday" can be replaced by time\.Thursday\.String\(\)`
	_ = fmt.Sprint("text before key Thursday")
	_ = fmt.Sprint("Thursday text after key")
	_ = fmt.Sprint("Tuesday") // want `"Tuesday" can be replaced by time\.Tuesday\.String\(\)`
	_ = fmt.Sprint("text before key Tuesday")
	_ = fmt.Sprint("Tuesday text after key")
	_ = fmt.Sprint("Wednesday") // want `"Wednesday" can be replaced by time\.Wednesday\.String\(\)`
	_ = fmt.Sprint("text before key Wednesday")
	_ = fmt.Sprint("Wednesday text after key")
}
