// Code generated by usestdlibvars, DO NOT EDIT.

package rpc_test

var (
	_ = "/_goRPC_"   // want `"/_goRPC_" can be replaced by rpc\.DefaultRPCPath`
	_ = "/debug/rpc" // want `"/debug/rpc" can be replaced by rpc\.DefaultDebugPath`
)

const (
	_ = "/_goRPC_"   // want `"/_goRPC_" can be replaced by rpc\.DefaultRPCPath`
	_ = "/debug/rpc" // want `"/debug/rpc" can be replaced by rpc\.DefaultDebugPath`
)

var (
	_ = func(s string) string { return s }("/_goRPC_")   // want `"/_goRPC_" can be replaced by rpc\.DefaultRPCPath`
	_ = func(s string) string { return s }("/debug/rpc") // want `"/debug/rpc" can be replaced by rpc\.DefaultDebugPath`
)
