// Code generated by usestdlibvars, DO NOT EDIT.

package crypto_test

import "fmt"

var (
	_ = "BLAKE2b-256" // want `"BLAKE2b-256" can be replaced by crypto\.BLAKE2b_256\.String\(\)`
	_ = "BLAKE2b-384" // want `"BLAKE2b-384" can be replaced by crypto\.BLAKE2b_384\.String\(\)`
	_ = "BLAKE2b-512" // want `"BLAKE2b-512" can be replaced by crypto\.BLAKE2b_512\.String\(\)`
	_ = "BLAKE2s-256" // want `"BLAKE2s-256" can be replaced by crypto\.BLAKE2s_256\.String\(\)`
	_ = "MD4"         // want `"MD4" can be replaced by crypto\.MD4\.String\(\)`
	_ = "MD5"         // want `"MD5" can be replaced by crypto\.MD5\.String\(\)`
	_ = "MD5+SHA1"    // want `"MD5\+SHA1" can be replaced by crypto\.MD5SHA1\.String\(\)`
	_ = "RIPEMD-160"  // want `"RIPEMD-160" can be replaced by crypto\.RIPEMD160\.String\(\)`
	_ = "SHA-1"       // want `"SHA-1" can be replaced by crypto\.SHA1\.String\(\)`
	_ = "SHA-224"     // want `"SHA-224" can be replaced by crypto\.SHA224\.String\(\)`
	_ = "SHA-256"     // want `"SHA-256" can be replaced by crypto\.SHA256\.String\(\)`
	_ = "SHA-384"     // want `"SHA-384" can be replaced by crypto\.SHA384\.String\(\)`
	_ = "SHA-512"     // want `"SHA-512" can be replaced by crypto\.SHA512\.String\(\)`
	_ = "SHA-512/224" // want `"SHA-512/224" can be replaced by crypto\.SHA512_224\.String\(\)`
	_ = "SHA-512/256" // want `"SHA-512/256" can be replaced by crypto\.SHA512_256\.String\(\)`
	_ = "SHA3-224"    // want `"SHA3-224" can be replaced by crypto\.SHA3_224\.String\(\)`
	_ = "SHA3-256"    // want `"SHA3-256" can be replaced by crypto\.SHA3_256\.String\(\)`
	_ = "SHA3-384"    // want `"SHA3-384" can be replaced by crypto\.SHA3_384\.String\(\)`
	_ = "SHA3-512"    // want `"SHA3-512" can be replaced by crypto\.SHA3_512\.String\(\)`
)

const (
	_ = "BLAKE2b-256" // want `"BLAKE2b-256" can be replaced by crypto\.BLAKE2b_256\.String\(\)`
	_ = "BLAKE2b-384" // want `"BLAKE2b-384" can be replaced by crypto\.BLAKE2b_384\.String\(\)`
	_ = "BLAKE2b-512" // want `"BLAKE2b-512" can be replaced by crypto\.BLAKE2b_512\.String\(\)`
	_ = "BLAKE2s-256" // want `"BLAKE2s-256" can be replaced by crypto\.BLAKE2s_256\.String\(\)`
	_ = "MD4"         // want `"MD4" can be replaced by crypto\.MD4\.String\(\)`
	_ = "MD5"         // want `"MD5" can be replaced by crypto\.MD5\.String\(\)`
	_ = "MD5+SHA1"    // want `"MD5\+SHA1" can be replaced by crypto\.MD5SHA1\.String\(\)`
	_ = "RIPEMD-160"  // want `"RIPEMD-160" can be replaced by crypto\.RIPEMD160\.String\(\)`
	_ = "SHA-1"       // want `"SHA-1" can be replaced by crypto\.SHA1\.String\(\)`
	_ = "SHA-224"     // want `"SHA-224" can be replaced by crypto\.SHA224\.String\(\)`
	_ = "SHA-256"     // want `"SHA-256" can be replaced by crypto\.SHA256\.String\(\)`
	_ = "SHA-384"     // want `"SHA-384" can be replaced by crypto\.SHA384\.String\(\)`
	_ = "SHA-512"     // want `"SHA-512" can be replaced by crypto\.SHA512\.String\(\)`
	_ = "SHA-512/224" // want `"SHA-512/224" can be replaced by crypto\.SHA512_224\.String\(\)`
	_ = "SHA-512/256" // want `"SHA-512/256" can be replaced by crypto\.SHA512_256\.String\(\)`
	_ = "SHA3-224"    // want `"SHA3-224" can be replaced by crypto\.SHA3_224\.String\(\)`
	_ = "SHA3-256"    // want `"SHA3-256" can be replaced by crypto\.SHA3_256\.String\(\)`
	_ = "SHA3-384"    // want `"SHA3-384" can be replaced by crypto\.SHA3_384\.String\(\)`
	_ = "SHA3-512"    // want `"SHA3-512" can be replaced by crypto\.SHA3_512\.String\(\)`
)

func _() {
	_ = func(s string) string { return s }("BLAKE2b-256") // want `"BLAKE2b-256" can be replaced by crypto\.BLAKE2b_256\.String\(\)`
	_ = func(s string) string { return s }("text before key BLAKE2b-256")
	_ = func(s string) string { return s }("BLAKE2b-256 text after key")
	_ = func(s string) string { return s }("BLAKE2b-384") // want `"BLAKE2b-384" can be replaced by crypto\.BLAKE2b_384\.String\(\)`
	_ = func(s string) string { return s }("text before key BLAKE2b-384")
	_ = func(s string) string { return s }("BLAKE2b-384 text after key")
	_ = func(s string) string { return s }("BLAKE2b-512") // want `"BLAKE2b-512" can be replaced by crypto\.BLAKE2b_512\.String\(\)`
	_ = func(s string) string { return s }("text before key BLAKE2b-512")
	_ = func(s string) string { return s }("BLAKE2b-512 text after key")
	_ = func(s string) string { return s }("BLAKE2s-256") // want `"BLAKE2s-256" can be replaced by crypto\.BLAKE2s_256\.String\(\)`
	_ = func(s string) string { return s }("text before key BLAKE2s-256")
	_ = func(s string) string { return s }("BLAKE2s-256 text after key")
	_ = func(s string) string { return s }("MD4") // want `"MD4" can be replaced by crypto\.MD4\.String\(\)`
	_ = func(s string) string { return s }("text before key MD4")
	_ = func(s string) string { return s }("MD4 text after key")
	_ = func(s string) string { return s }("MD5") // want `"MD5" can be replaced by crypto\.MD5\.String\(\)`
	_ = func(s string) string { return s }("text before key MD5")
	_ = func(s string) string { return s }("MD5 text after key")
	_ = func(s string) string { return s }("MD5+SHA1") // want `"MD5\+SHA1" can be replaced by crypto\.MD5SHA1\.String\(\)`
	_ = func(s string) string { return s }("text before key MD5+SHA1")
	_ = func(s string) string { return s }("MD5+SHA1 text after key")
	_ = func(s string) string { return s }("RIPEMD-160") // want `"RIPEMD-160" can be replaced by crypto\.RIPEMD160\.String\(\)`
	_ = func(s string) string { return s }("text before key RIPEMD-160")
	_ = func(s string) string { return s }("RIPEMD-160 text after key")
	_ = func(s string) string { return s }("SHA-1") // want `"SHA-1" can be replaced by crypto\.SHA1\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA-1")
	_ = func(s string) string { return s }("SHA-1 text after key")
	_ = func(s string) string { return s }("SHA-224") // want `"SHA-224" can be replaced by crypto\.SHA224\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA-224")
	_ = func(s string) string { return s }("SHA-224 text after key")
	_ = func(s string) string { return s }("SHA-256") // want `"SHA-256" can be replaced by crypto\.SHA256\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA-256")
	_ = func(s string) string { return s }("SHA-256 text after key")
	_ = func(s string) string { return s }("SHA-384") // want `"SHA-384" can be replaced by crypto\.SHA384\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA-384")
	_ = func(s string) string { return s }("SHA-384 text after key")
	_ = func(s string) string { return s }("SHA-512") // want `"SHA-512" can be replaced by crypto\.SHA512\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA-512")
	_ = func(s string) string { return s }("SHA-512 text after key")
	_ = func(s string) string { return s }("SHA-512/224") // want `"SHA-512/224" can be replaced by crypto\.SHA512_224\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA-512/224")
	_ = func(s string) string { return s }("SHA-512/224 text after key")
	_ = func(s string) string { return s }("SHA-512/256") // want `"SHA-512/256" can be replaced by crypto\.SHA512_256\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA-512/256")
	_ = func(s string) string { return s }("SHA-512/256 text after key")
	_ = func(s string) string { return s }("SHA3-224") // want `"SHA3-224" can be replaced by crypto\.SHA3_224\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA3-224")
	_ = func(s string) string { return s }("SHA3-224 text after key")
	_ = func(s string) string { return s }("SHA3-256") // want `"SHA3-256" can be replaced by crypto\.SHA3_256\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA3-256")
	_ = func(s string) string { return s }("SHA3-256 text after key")
	_ = func(s string) string { return s }("SHA3-384") // want `"SHA3-384" can be replaced by crypto\.SHA3_384\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA3-384")
	_ = func(s string) string { return s }("SHA3-384 text after key")
	_ = func(s string) string { return s }("SHA3-512") // want `"SHA3-512" can be replaced by crypto\.SHA3_512\.String\(\)`
	_ = func(s string) string { return s }("text before key SHA3-512")
	_ = func(s string) string { return s }("SHA3-512 text after key")
}

func _() {
	_ = fmt.Sprint("BLAKE2b-256") // want `"BLAKE2b-256" can be replaced by crypto\.BLAKE2b_256\.String\(\)`
	_ = fmt.Sprint("text before key BLAKE2b-256")
	_ = fmt.Sprint("BLAKE2b-256 text after key")
	_ = fmt.Sprint("BLAKE2b-384") // want `"BLAKE2b-384" can be replaced by crypto\.BLAKE2b_384\.String\(\)`
	_ = fmt.Sprint("text before key BLAKE2b-384")
	_ = fmt.Sprint("BLAKE2b-384 text after key")
	_ = fmt.Sprint("BLAKE2b-512") // want `"BLAKE2b-512" can be replaced by crypto\.BLAKE2b_512\.String\(\)`
	_ = fmt.Sprint("text before key BLAKE2b-512")
	_ = fmt.Sprint("BLAKE2b-512 text after key")
	_ = fmt.Sprint("BLAKE2s-256") // want `"BLAKE2s-256" can be replaced by crypto\.BLAKE2s_256\.String\(\)`
	_ = fmt.Sprint("text before key BLAKE2s-256")
	_ = fmt.Sprint("BLAKE2s-256 text after key")
	_ = fmt.Sprint("MD4") // want `"MD4" can be replaced by crypto\.MD4\.String\(\)`
	_ = fmt.Sprint("text before key MD4")
	_ = fmt.Sprint("MD4 text after key")
	_ = fmt.Sprint("MD5") // want `"MD5" can be replaced by crypto\.MD5\.String\(\)`
	_ = fmt.Sprint("text before key MD5")
	_ = fmt.Sprint("MD5 text after key")
	_ = fmt.Sprint("MD5+SHA1") // want `"MD5\+SHA1" can be replaced by crypto\.MD5SHA1\.String\(\)`
	_ = fmt.Sprint("text before key MD5+SHA1")
	_ = fmt.Sprint("MD5+SHA1 text after key")
	_ = fmt.Sprint("RIPEMD-160") // want `"RIPEMD-160" can be replaced by crypto\.RIPEMD160\.String\(\)`
	_ = fmt.Sprint("text before key RIPEMD-160")
	_ = fmt.Sprint("RIPEMD-160 text after key")
	_ = fmt.Sprint("SHA-1") // want `"SHA-1" can be replaced by crypto\.SHA1\.String\(\)`
	_ = fmt.Sprint("text before key SHA-1")
	_ = fmt.Sprint("SHA-1 text after key")
	_ = fmt.Sprint("SHA-224") // want `"SHA-224" can be replaced by crypto\.SHA224\.String\(\)`
	_ = fmt.Sprint("text before key SHA-224")
	_ = fmt.Sprint("SHA-224 text after key")
	_ = fmt.Sprint("SHA-256") // want `"SHA-256" can be replaced by crypto\.SHA256\.String\(\)`
	_ = fmt.Sprint("text before key SHA-256")
	_ = fmt.Sprint("SHA-256 text after key")
	_ = fmt.Sprint("SHA-384") // want `"SHA-384" can be replaced by crypto\.SHA384\.String\(\)`
	_ = fmt.Sprint("text before key SHA-384")
	_ = fmt.Sprint("SHA-384 text after key")
	_ = fmt.Sprint("SHA-512") // want `"SHA-512" can be replaced by crypto\.SHA512\.String\(\)`
	_ = fmt.Sprint("text before key SHA-512")
	_ = fmt.Sprint("SHA-512 text after key")
	_ = fmt.Sprint("SHA-512/224") // want `"SHA-512/224" can be replaced by crypto\.SHA512_224\.String\(\)`
	_ = fmt.Sprint("text before key SHA-512/224")
	_ = fmt.Sprint("SHA-512/224 text after key")
	_ = fmt.Sprint("SHA-512/256") // want `"SHA-512/256" can be replaced by crypto\.SHA512_256\.String\(\)`
	_ = fmt.Sprint("text before key SHA-512/256")
	_ = fmt.Sprint("SHA-512/256 text after key")
	_ = fmt.Sprint("SHA3-224") // want `"SHA3-224" can be replaced by crypto\.SHA3_224\.String\(\)`
	_ = fmt.Sprint("text before key SHA3-224")
	_ = fmt.Sprint("SHA3-224 text after key")
	_ = fmt.Sprint("SHA3-256") // want `"SHA3-256" can be replaced by crypto\.SHA3_256\.String\(\)`
	_ = fmt.Sprint("text before key SHA3-256")
	_ = fmt.Sprint("SHA3-256 text after key")
	_ = fmt.Sprint("SHA3-384") // want `"SHA3-384" can be replaced by crypto\.SHA3_384\.String\(\)`
	_ = fmt.Sprint("text before key SHA3-384")
	_ = fmt.Sprint("SHA3-384 text after key")
	_ = fmt.Sprint("SHA3-512") // want `"SHA3-512" can be replaced by crypto\.SHA3_512\.String\(\)`
	_ = fmt.Sprint("text before key SHA3-512")
	_ = fmt.Sprint("SHA3-512 text after key")
}
