// Code generated by usestdlibvars, DO NOT EDIT.

package http_test

import "net/http"

func _() error {
	resp, err := http.DefaultClient.Do(&http.Request{})
	if err != nil {
		return err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode < 100 {
		return nil
	} else if resp.StatusCode < 100 {
		return nil
	}
	if resp.StatusCode < 101 {
		return nil
	} else if resp.StatusCode < 101 {
		return nil
	}
	if resp.StatusCode < 102 {
		return nil
	} else if resp.StatusCode < 102 {
		return nil
	}
	if resp.StatusCode < 103 {
		return nil
	} else if resp.StatusCode < 103 {
		return nil
	}
	if resp.StatusCode < 200 {
		return nil
	} else if resp.StatusCode < 200 {
		return nil
	}
	if resp.StatusCode < 201 {
		return nil
	} else if resp.StatusCode < 201 {
		return nil
	}
	if resp.StatusCode < 202 {
		return nil
	} else if resp.StatusCode < 202 {
		return nil
	}
	if resp.StatusCode < 203 {
		return nil
	} else if resp.StatusCode < 203 {
		return nil
	}
	if resp.StatusCode < 204 {
		return nil
	} else if resp.StatusCode < 204 {
		return nil
	}
	if resp.StatusCode < 205 {
		return nil
	} else if resp.StatusCode < 205 {
		return nil
	}
	if resp.StatusCode < 206 {
		return nil
	} else if resp.StatusCode < 206 {
		return nil
	}
	if resp.StatusCode < 207 {
		return nil
	} else if resp.StatusCode < 207 {
		return nil
	}
	if resp.StatusCode < 208 {
		return nil
	} else if resp.StatusCode < 208 {
		return nil
	}
	if resp.StatusCode < 226 {
		return nil
	} else if resp.StatusCode < 226 {
		return nil
	}
	if resp.StatusCode < 300 {
		return nil
	} else if resp.StatusCode < 300 {
		return nil
	}
	if resp.StatusCode < 301 {
		return nil
	} else if resp.StatusCode < 301 {
		return nil
	}
	if resp.StatusCode < 302 {
		return nil
	} else if resp.StatusCode < 302 {
		return nil
	}
	if resp.StatusCode < 303 {
		return nil
	} else if resp.StatusCode < 303 {
		return nil
	}
	if resp.StatusCode < 304 {
		return nil
	} else if resp.StatusCode < 304 {
		return nil
	}
	if resp.StatusCode < 305 {
		return nil
	} else if resp.StatusCode < 305 {
		return nil
	}
	if resp.StatusCode < 307 {
		return nil
	} else if resp.StatusCode < 307 {
		return nil
	}
	if resp.StatusCode < 308 {
		return nil
	} else if resp.StatusCode < 308 {
		return nil
	}
	if resp.StatusCode < 400 {
		return nil
	} else if resp.StatusCode < 400 {
		return nil
	}
	if resp.StatusCode < 401 {
		return nil
	} else if resp.StatusCode < 401 {
		return nil
	}
	if resp.StatusCode < 402 {
		return nil
	} else if resp.StatusCode < 402 {
		return nil
	}
	if resp.StatusCode < 403 {
		return nil
	} else if resp.StatusCode < 403 {
		return nil
	}
	if resp.StatusCode < 404 {
		return nil
	} else if resp.StatusCode < 404 {
		return nil
	}
	if resp.StatusCode < 405 {
		return nil
	} else if resp.StatusCode < 405 {
		return nil
	}
	if resp.StatusCode < 406 {
		return nil
	} else if resp.StatusCode < 406 {
		return nil
	}
	if resp.StatusCode < 407 {
		return nil
	} else if resp.StatusCode < 407 {
		return nil
	}
	if resp.StatusCode < 408 {
		return nil
	} else if resp.StatusCode < 408 {
		return nil
	}
	if resp.StatusCode < 409 {
		return nil
	} else if resp.StatusCode < 409 {
		return nil
	}
	if resp.StatusCode < 410 {
		return nil
	} else if resp.StatusCode < 410 {
		return nil
	}
	if resp.StatusCode < 411 {
		return nil
	} else if resp.StatusCode < 411 {
		return nil
	}
	if resp.StatusCode < 412 {
		return nil
	} else if resp.StatusCode < 412 {
		return nil
	}
	if resp.StatusCode < 413 {
		return nil
	} else if resp.StatusCode < 413 {
		return nil
	}
	if resp.StatusCode < 414 {
		return nil
	} else if resp.StatusCode < 414 {
		return nil
	}
	if resp.StatusCode < 415 {
		return nil
	} else if resp.StatusCode < 415 {
		return nil
	}
	if resp.StatusCode < 416 {
		return nil
	} else if resp.StatusCode < 416 {
		return nil
	}
	if resp.StatusCode < 417 {
		return nil
	} else if resp.StatusCode < 417 {
		return nil
	}
	if resp.StatusCode < 418 {
		return nil
	} else if resp.StatusCode < 418 {
		return nil
	}
	if resp.StatusCode < 421 {
		return nil
	} else if resp.StatusCode < 421 {
		return nil
	}
	if resp.StatusCode < 422 {
		return nil
	} else if resp.StatusCode < 422 {
		return nil
	}
	if resp.StatusCode < 423 {
		return nil
	} else if resp.StatusCode < 423 {
		return nil
	}
	if resp.StatusCode < 424 {
		return nil
	} else if resp.StatusCode < 424 {
		return nil
	}
	if resp.StatusCode < 425 {
		return nil
	} else if resp.StatusCode < 425 {
		return nil
	}
	if resp.StatusCode < 426 {
		return nil
	} else if resp.StatusCode < 426 {
		return nil
	}
	if resp.StatusCode < 428 {
		return nil
	} else if resp.StatusCode < 428 {
		return nil
	}
	if resp.StatusCode < 429 {
		return nil
	} else if resp.StatusCode < 429 {
		return nil
	}
	if resp.StatusCode < 431 {
		return nil
	} else if resp.StatusCode < 431 {
		return nil
	}
	if resp.StatusCode < 451 {
		return nil
	} else if resp.StatusCode < 451 {
		return nil
	}
	if resp.StatusCode < 500 {
		return nil
	} else if resp.StatusCode < 500 {
		return nil
	}
	if resp.StatusCode < 501 {
		return nil
	} else if resp.StatusCode < 501 {
		return nil
	}
	if resp.StatusCode < 502 {
		return nil
	} else if resp.StatusCode < 502 {
		return nil
	}
	if resp.StatusCode < 503 {
		return nil
	} else if resp.StatusCode < 503 {
		return nil
	}
	if resp.StatusCode < 504 {
		return nil
	} else if resp.StatusCode < 504 {
		return nil
	}
	if resp.StatusCode < 505 {
		return nil
	} else if resp.StatusCode < 505 {
		return nil
	}
	if resp.StatusCode < 506 {
		return nil
	} else if resp.StatusCode < 506 {
		return nil
	}
	if resp.StatusCode < 507 {
		return nil
	} else if resp.StatusCode < 507 {
		return nil
	}
	if resp.StatusCode < 508 {
		return nil
	} else if resp.StatusCode < 508 {
		return nil
	}
	if resp.StatusCode < 510 {
		return nil
	} else if resp.StatusCode < 510 {
		return nil
	}
	if resp.StatusCode < 511 {
		return nil
	} else if resp.StatusCode < 511 {
		return nil
	}
	if resp.StatusCode > 100 {
		return nil
	} else if resp.StatusCode > 100 {
		return nil
	}
	if resp.StatusCode > 101 {
		return nil
	} else if resp.StatusCode > 101 {
		return nil
	}
	if resp.StatusCode > 102 {
		return nil
	} else if resp.StatusCode > 102 {
		return nil
	}
	if resp.StatusCode > 103 {
		return nil
	} else if resp.StatusCode > 103 {
		return nil
	}
	if resp.StatusCode > 200 {
		return nil
	} else if resp.StatusCode > 200 {
		return nil
	}
	if resp.StatusCode > 201 {
		return nil
	} else if resp.StatusCode > 201 {
		return nil
	}
	if resp.StatusCode > 202 {
		return nil
	} else if resp.StatusCode > 202 {
		return nil
	}
	if resp.StatusCode > 203 {
		return nil
	} else if resp.StatusCode > 203 {
		return nil
	}
	if resp.StatusCode > 204 {
		return nil
	} else if resp.StatusCode > 204 {
		return nil
	}
	if resp.StatusCode > 205 {
		return nil
	} else if resp.StatusCode > 205 {
		return nil
	}
	if resp.StatusCode > 206 {
		return nil
	} else if resp.StatusCode > 206 {
		return nil
	}
	if resp.StatusCode > 207 {
		return nil
	} else if resp.StatusCode > 207 {
		return nil
	}
	if resp.StatusCode > 208 {
		return nil
	} else if resp.StatusCode > 208 {
		return nil
	}
	if resp.StatusCode > 226 {
		return nil
	} else if resp.StatusCode > 226 {
		return nil
	}
	if resp.StatusCode > 300 {
		return nil
	} else if resp.StatusCode > 300 {
		return nil
	}
	if resp.StatusCode > 301 {
		return nil
	} else if resp.StatusCode > 301 {
		return nil
	}
	if resp.StatusCode > 302 {
		return nil
	} else if resp.StatusCode > 302 {
		return nil
	}
	if resp.StatusCode > 303 {
		return nil
	} else if resp.StatusCode > 303 {
		return nil
	}
	if resp.StatusCode > 304 {
		return nil
	} else if resp.StatusCode > 304 {
		return nil
	}
	if resp.StatusCode > 305 {
		return nil
	} else if resp.StatusCode > 305 {
		return nil
	}
	if resp.StatusCode > 307 {
		return nil
	} else if resp.StatusCode > 307 {
		return nil
	}
	if resp.StatusCode > 308 {
		return nil
	} else if resp.StatusCode > 308 {
		return nil
	}
	if resp.StatusCode > 400 {
		return nil
	} else if resp.StatusCode > 400 {
		return nil
	}
	if resp.StatusCode > 401 {
		return nil
	} else if resp.StatusCode > 401 {
		return nil
	}
	if resp.StatusCode > 402 {
		return nil
	} else if resp.StatusCode > 402 {
		return nil
	}
	if resp.StatusCode > 403 {
		return nil
	} else if resp.StatusCode > 403 {
		return nil
	}
	if resp.StatusCode > 404 {
		return nil
	} else if resp.StatusCode > 404 {
		return nil
	}
	if resp.StatusCode > 405 {
		return nil
	} else if resp.StatusCode > 405 {
		return nil
	}
	if resp.StatusCode > 406 {
		return nil
	} else if resp.StatusCode > 406 {
		return nil
	}
	if resp.StatusCode > 407 {
		return nil
	} else if resp.StatusCode > 407 {
		return nil
	}
	if resp.StatusCode > 408 {
		return nil
	} else if resp.StatusCode > 408 {
		return nil
	}
	if resp.StatusCode > 409 {
		return nil
	} else if resp.StatusCode > 409 {
		return nil
	}
	if resp.StatusCode > 410 {
		return nil
	} else if resp.StatusCode > 410 {
		return nil
	}
	if resp.StatusCode > 411 {
		return nil
	} else if resp.StatusCode > 411 {
		return nil
	}
	if resp.StatusCode > 412 {
		return nil
	} else if resp.StatusCode > 412 {
		return nil
	}
	if resp.StatusCode > 413 {
		return nil
	} else if resp.StatusCode > 413 {
		return nil
	}
	if resp.StatusCode > 414 {
		return nil
	} else if resp.StatusCode > 414 {
		return nil
	}
	if resp.StatusCode > 415 {
		return nil
	} else if resp.StatusCode > 415 {
		return nil
	}
	if resp.StatusCode > 416 {
		return nil
	} else if resp.StatusCode > 416 {
		return nil
	}
	if resp.StatusCode > 417 {
		return nil
	} else if resp.StatusCode > 417 {
		return nil
	}
	if resp.StatusCode > 418 {
		return nil
	} else if resp.StatusCode > 418 {
		return nil
	}
	if resp.StatusCode > 421 {
		return nil
	} else if resp.StatusCode > 421 {
		return nil
	}
	if resp.StatusCode > 422 {
		return nil
	} else if resp.StatusCode > 422 {
		return nil
	}
	if resp.StatusCode > 423 {
		return nil
	} else if resp.StatusCode > 423 {
		return nil
	}
	if resp.StatusCode > 424 {
		return nil
	} else if resp.StatusCode > 424 {
		return nil
	}
	if resp.StatusCode > 425 {
		return nil
	} else if resp.StatusCode > 425 {
		return nil
	}
	if resp.StatusCode > 426 {
		return nil
	} else if resp.StatusCode > 426 {
		return nil
	}
	if resp.StatusCode > 428 {
		return nil
	} else if resp.StatusCode > 428 {
		return nil
	}
	if resp.StatusCode > 429 {
		return nil
	} else if resp.StatusCode > 429 {
		return nil
	}
	if resp.StatusCode > 431 {
		return nil
	} else if resp.StatusCode > 431 {
		return nil
	}
	if resp.StatusCode > 451 {
		return nil
	} else if resp.StatusCode > 451 {
		return nil
	}
	if resp.StatusCode > 500 {
		return nil
	} else if resp.StatusCode > 500 {
		return nil
	}
	if resp.StatusCode > 501 {
		return nil
	} else if resp.StatusCode > 501 {
		return nil
	}
	if resp.StatusCode > 502 {
		return nil
	} else if resp.StatusCode > 502 {
		return nil
	}
	if resp.StatusCode > 503 {
		return nil
	} else if resp.StatusCode > 503 {
		return nil
	}
	if resp.StatusCode > 504 {
		return nil
	} else if resp.StatusCode > 504 {
		return nil
	}
	if resp.StatusCode > 505 {
		return nil
	} else if resp.StatusCode > 505 {
		return nil
	}
	if resp.StatusCode > 506 {
		return nil
	} else if resp.StatusCode > 506 {
		return nil
	}
	if resp.StatusCode > 507 {
		return nil
	} else if resp.StatusCode > 507 {
		return nil
	}
	if resp.StatusCode > 508 {
		return nil
	} else if resp.StatusCode > 508 {
		return nil
	}
	if resp.StatusCode > 510 {
		return nil
	} else if resp.StatusCode > 510 {
		return nil
	}
	if resp.StatusCode > 511 {
		return nil
	} else if resp.StatusCode > 511 {
		return nil
	}
	if resp.StatusCode <= 100 {
		return nil
	} else if resp.StatusCode < 100 {
		return nil
	}
	if resp.StatusCode <= 101 {
		return nil
	} else if resp.StatusCode < 101 {
		return nil
	}
	if resp.StatusCode <= 102 {
		return nil
	} else if resp.StatusCode < 102 {
		return nil
	}
	if resp.StatusCode <= 103 {
		return nil
	} else if resp.StatusCode < 103 {
		return nil
	}
	if resp.StatusCode <= 200 {
		return nil
	} else if resp.StatusCode < 200 {
		return nil
	}
	if resp.StatusCode <= 201 {
		return nil
	} else if resp.StatusCode < 201 {
		return nil
	}
	if resp.StatusCode <= 202 {
		return nil
	} else if resp.StatusCode < 202 {
		return nil
	}
	if resp.StatusCode <= 203 {
		return nil
	} else if resp.StatusCode < 203 {
		return nil
	}
	if resp.StatusCode <= 204 {
		return nil
	} else if resp.StatusCode < 204 {
		return nil
	}
	if resp.StatusCode <= 205 {
		return nil
	} else if resp.StatusCode < 205 {
		return nil
	}
	if resp.StatusCode <= 206 {
		return nil
	} else if resp.StatusCode < 206 {
		return nil
	}
	if resp.StatusCode <= 207 {
		return nil
	} else if resp.StatusCode < 207 {
		return nil
	}
	if resp.StatusCode <= 208 {
		return nil
	} else if resp.StatusCode < 208 {
		return nil
	}
	if resp.StatusCode <= 226 {
		return nil
	} else if resp.StatusCode < 226 {
		return nil
	}
	if resp.StatusCode <= 300 {
		return nil
	} else if resp.StatusCode < 300 {
		return nil
	}
	if resp.StatusCode <= 301 {
		return nil
	} else if resp.StatusCode < 301 {
		return nil
	}
	if resp.StatusCode <= 302 {
		return nil
	} else if resp.StatusCode < 302 {
		return nil
	}
	if resp.StatusCode <= 303 {
		return nil
	} else if resp.StatusCode < 303 {
		return nil
	}
	if resp.StatusCode <= 304 {
		return nil
	} else if resp.StatusCode < 304 {
		return nil
	}
	if resp.StatusCode <= 305 {
		return nil
	} else if resp.StatusCode < 305 {
		return nil
	}
	if resp.StatusCode <= 307 {
		return nil
	} else if resp.StatusCode < 307 {
		return nil
	}
	if resp.StatusCode <= 308 {
		return nil
	} else if resp.StatusCode < 308 {
		return nil
	}
	if resp.StatusCode <= 400 {
		return nil
	} else if resp.StatusCode < 400 {
		return nil
	}
	if resp.StatusCode <= 401 {
		return nil
	} else if resp.StatusCode < 401 {
		return nil
	}
	if resp.StatusCode <= 402 {
		return nil
	} else if resp.StatusCode < 402 {
		return nil
	}
	if resp.StatusCode <= 403 {
		return nil
	} else if resp.StatusCode < 403 {
		return nil
	}
	if resp.StatusCode <= 404 {
		return nil
	} else if resp.StatusCode < 404 {
		return nil
	}
	if resp.StatusCode <= 405 {
		return nil
	} else if resp.StatusCode < 405 {
		return nil
	}
	if resp.StatusCode <= 406 {
		return nil
	} else if resp.StatusCode < 406 {
		return nil
	}
	if resp.StatusCode <= 407 {
		return nil
	} else if resp.StatusCode < 407 {
		return nil
	}
	if resp.StatusCode <= 408 {
		return nil
	} else if resp.StatusCode < 408 {
		return nil
	}
	if resp.StatusCode <= 409 {
		return nil
	} else if resp.StatusCode < 409 {
		return nil
	}
	if resp.StatusCode <= 410 {
		return nil
	} else if resp.StatusCode < 410 {
		return nil
	}
	if resp.StatusCode <= 411 {
		return nil
	} else if resp.StatusCode < 411 {
		return nil
	}
	if resp.StatusCode <= 412 {
		return nil
	} else if resp.StatusCode < 412 {
		return nil
	}
	if resp.StatusCode <= 413 {
		return nil
	} else if resp.StatusCode < 413 {
		return nil
	}
	if resp.StatusCode <= 414 {
		return nil
	} else if resp.StatusCode < 414 {
		return nil
	}
	if resp.StatusCode <= 415 {
		return nil
	} else if resp.StatusCode < 415 {
		return nil
	}
	if resp.StatusCode <= 416 {
		return nil
	} else if resp.StatusCode < 416 {
		return nil
	}
	if resp.StatusCode <= 417 {
		return nil
	} else if resp.StatusCode < 417 {
		return nil
	}
	if resp.StatusCode <= 418 {
		return nil
	} else if resp.StatusCode < 418 {
		return nil
	}
	if resp.StatusCode <= 421 {
		return nil
	} else if resp.StatusCode < 421 {
		return nil
	}
	if resp.StatusCode <= 422 {
		return nil
	} else if resp.StatusCode < 422 {
		return nil
	}
	if resp.StatusCode <= 423 {
		return nil
	} else if resp.StatusCode < 423 {
		return nil
	}
	if resp.StatusCode <= 424 {
		return nil
	} else if resp.StatusCode < 424 {
		return nil
	}
	if resp.StatusCode <= 425 {
		return nil
	} else if resp.StatusCode < 425 {
		return nil
	}
	if resp.StatusCode <= 426 {
		return nil
	} else if resp.StatusCode < 426 {
		return nil
	}
	if resp.StatusCode <= 428 {
		return nil
	} else if resp.StatusCode < 428 {
		return nil
	}
	if resp.StatusCode <= 429 {
		return nil
	} else if resp.StatusCode < 429 {
		return nil
	}
	if resp.StatusCode <= 431 {
		return nil
	} else if resp.StatusCode < 431 {
		return nil
	}
	if resp.StatusCode <= 451 {
		return nil
	} else if resp.StatusCode < 451 {
		return nil
	}
	if resp.StatusCode <= 500 {
		return nil
	} else if resp.StatusCode < 500 {
		return nil
	}
	if resp.StatusCode <= 501 {
		return nil
	} else if resp.StatusCode < 501 {
		return nil
	}
	if resp.StatusCode <= 502 {
		return nil
	} else if resp.StatusCode < 502 {
		return nil
	}
	if resp.StatusCode <= 503 {
		return nil
	} else if resp.StatusCode < 503 {
		return nil
	}
	if resp.StatusCode <= 504 {
		return nil
	} else if resp.StatusCode < 504 {
		return nil
	}
	if resp.StatusCode <= 505 {
		return nil
	} else if resp.StatusCode < 505 {
		return nil
	}
	if resp.StatusCode <= 506 {
		return nil
	} else if resp.StatusCode < 506 {
		return nil
	}
	if resp.StatusCode <= 507 {
		return nil
	} else if resp.StatusCode < 507 {
		return nil
	}
	if resp.StatusCode <= 508 {
		return nil
	} else if resp.StatusCode < 508 {
		return nil
	}
	if resp.StatusCode <= 510 {
		return nil
	} else if resp.StatusCode < 510 {
		return nil
	}
	if resp.StatusCode <= 511 {
		return nil
	} else if resp.StatusCode < 511 {
		return nil
	}
	if resp.StatusCode >= 100 {
		return nil
	} else if resp.StatusCode > 100 {
		return nil
	}
	if resp.StatusCode >= 101 {
		return nil
	} else if resp.StatusCode > 101 {
		return nil
	}
	if resp.StatusCode >= 102 {
		return nil
	} else if resp.StatusCode > 102 {
		return nil
	}
	if resp.StatusCode >= 103 {
		return nil
	} else if resp.StatusCode > 103 {
		return nil
	}
	if resp.StatusCode >= 200 {
		return nil
	} else if resp.StatusCode > 200 {
		return nil
	}
	if resp.StatusCode >= 201 {
		return nil
	} else if resp.StatusCode > 201 {
		return nil
	}
	if resp.StatusCode >= 202 {
		return nil
	} else if resp.StatusCode > 202 {
		return nil
	}
	if resp.StatusCode >= 203 {
		return nil
	} else if resp.StatusCode > 203 {
		return nil
	}
	if resp.StatusCode >= 204 {
		return nil
	} else if resp.StatusCode > 204 {
		return nil
	}
	if resp.StatusCode >= 205 {
		return nil
	} else if resp.StatusCode > 205 {
		return nil
	}
	if resp.StatusCode >= 206 {
		return nil
	} else if resp.StatusCode > 206 {
		return nil
	}
	if resp.StatusCode >= 207 {
		return nil
	} else if resp.StatusCode > 207 {
		return nil
	}
	if resp.StatusCode >= 208 {
		return nil
	} else if resp.StatusCode > 208 {
		return nil
	}
	if resp.StatusCode >= 226 {
		return nil
	} else if resp.StatusCode > 226 {
		return nil
	}
	if resp.StatusCode >= 300 {
		return nil
	} else if resp.StatusCode > 300 {
		return nil
	}
	if resp.StatusCode >= 301 {
		return nil
	} else if resp.StatusCode > 301 {
		return nil
	}
	if resp.StatusCode >= 302 {
		return nil
	} else if resp.StatusCode > 302 {
		return nil
	}
	if resp.StatusCode >= 303 {
		return nil
	} else if resp.StatusCode > 303 {
		return nil
	}
	if resp.StatusCode >= 304 {
		return nil
	} else if resp.StatusCode > 304 {
		return nil
	}
	if resp.StatusCode >= 305 {
		return nil
	} else if resp.StatusCode > 305 {
		return nil
	}
	if resp.StatusCode >= 307 {
		return nil
	} else if resp.StatusCode > 307 {
		return nil
	}
	if resp.StatusCode >= 308 {
		return nil
	} else if resp.StatusCode > 308 {
		return nil
	}
	if resp.StatusCode >= 400 {
		return nil
	} else if resp.StatusCode > 400 {
		return nil
	}
	if resp.StatusCode >= 401 {
		return nil
	} else if resp.StatusCode > 401 {
		return nil
	}
	if resp.StatusCode >= 402 {
		return nil
	} else if resp.StatusCode > 402 {
		return nil
	}
	if resp.StatusCode >= 403 {
		return nil
	} else if resp.StatusCode > 403 {
		return nil
	}
	if resp.StatusCode >= 404 {
		return nil
	} else if resp.StatusCode > 404 {
		return nil
	}
	if resp.StatusCode >= 405 {
		return nil
	} else if resp.StatusCode > 405 {
		return nil
	}
	if resp.StatusCode >= 406 {
		return nil
	} else if resp.StatusCode > 406 {
		return nil
	}
	if resp.StatusCode >= 407 {
		return nil
	} else if resp.StatusCode > 407 {
		return nil
	}
	if resp.StatusCode >= 408 {
		return nil
	} else if resp.StatusCode > 408 {
		return nil
	}
	if resp.StatusCode >= 409 {
		return nil
	} else if resp.StatusCode > 409 {
		return nil
	}
	if resp.StatusCode >= 410 {
		return nil
	} else if resp.StatusCode > 410 {
		return nil
	}
	if resp.StatusCode >= 411 {
		return nil
	} else if resp.StatusCode > 411 {
		return nil
	}
	if resp.StatusCode >= 412 {
		return nil
	} else if resp.StatusCode > 412 {
		return nil
	}
	if resp.StatusCode >= 413 {
		return nil
	} else if resp.StatusCode > 413 {
		return nil
	}
	if resp.StatusCode >= 414 {
		return nil
	} else if resp.StatusCode > 414 {
		return nil
	}
	if resp.StatusCode >= 415 {
		return nil
	} else if resp.StatusCode > 415 {
		return nil
	}
	if resp.StatusCode >= 416 {
		return nil
	} else if resp.StatusCode > 416 {
		return nil
	}
	if resp.StatusCode >= 417 {
		return nil
	} else if resp.StatusCode > 417 {
		return nil
	}
	if resp.StatusCode >= 418 {
		return nil
	} else if resp.StatusCode > 418 {
		return nil
	}
	if resp.StatusCode >= 421 {
		return nil
	} else if resp.StatusCode > 421 {
		return nil
	}
	if resp.StatusCode >= 422 {
		return nil
	} else if resp.StatusCode > 422 {
		return nil
	}
	if resp.StatusCode >= 423 {
		return nil
	} else if resp.StatusCode > 423 {
		return nil
	}
	if resp.StatusCode >= 424 {
		return nil
	} else if resp.StatusCode > 424 {
		return nil
	}
	if resp.StatusCode >= 425 {
		return nil
	} else if resp.StatusCode > 425 {
		return nil
	}
	if resp.StatusCode >= 426 {
		return nil
	} else if resp.StatusCode > 426 {
		return nil
	}
	if resp.StatusCode >= 428 {
		return nil
	} else if resp.StatusCode > 428 {
		return nil
	}
	if resp.StatusCode >= 429 {
		return nil
	} else if resp.StatusCode > 429 {
		return nil
	}
	if resp.StatusCode >= 431 {
		return nil
	} else if resp.StatusCode > 431 {
		return nil
	}
	if resp.StatusCode >= 451 {
		return nil
	} else if resp.StatusCode > 451 {
		return nil
	}
	if resp.StatusCode >= 500 {
		return nil
	} else if resp.StatusCode > 500 {
		return nil
	}
	if resp.StatusCode >= 501 {
		return nil
	} else if resp.StatusCode > 501 {
		return nil
	}
	if resp.StatusCode >= 502 {
		return nil
	} else if resp.StatusCode > 502 {
		return nil
	}
	if resp.StatusCode >= 503 {
		return nil
	} else if resp.StatusCode > 503 {
		return nil
	}
	if resp.StatusCode >= 504 {
		return nil
	} else if resp.StatusCode > 504 {
		return nil
	}
	if resp.StatusCode >= 505 {
		return nil
	} else if resp.StatusCode > 505 {
		return nil
	}
	if resp.StatusCode >= 506 {
		return nil
	} else if resp.StatusCode > 506 {
		return nil
	}
	if resp.StatusCode >= 507 {
		return nil
	} else if resp.StatusCode > 507 {
		return nil
	}
	if resp.StatusCode >= 508 {
		return nil
	} else if resp.StatusCode > 508 {
		return nil
	}
	if resp.StatusCode >= 510 {
		return nil
	} else if resp.StatusCode > 510 {
		return nil
	}
	if resp.StatusCode >= 511 {
		return nil
	} else if resp.StatusCode > 511 {
		return nil
	}
	return nil
}
