// Code generated by usestdlibvars, DO NOT EDIT.

package http_test

import "net/http"

func _() {
	_, _ = http.NewRequest(http.MethodGet, "", nil) // want `"nil" can be replaced by http\.NoBody`
}

func _() {
	_, _ = http.NewRequestWithContext(nil, http.MethodGet, "", nil) // want `"nil" can be replaced by http\.NoBody`
}
