// Code generated by usestdlibvars, DO NOT EDIT.

package os_test

var (
	_ = "/dev/null" // want `"/dev/null" can be replaced by os\.DevNull`
)

const (
	_ = "/dev/null" // want `"/dev/null" can be replaced by os\.DevNull`
)

var (
	_ = func(s string) string { return s }("/dev/null") // want `"/dev/null" can be replaced by os\.DevNull`
)
