// Code generated by usestdlibvars, DO NOT EDIT.

package constant_test

var (
	_ = "Bool"    // want `"Bool" can be replaced by constant\.Bool\.String\(\)`
	_ = "Complex" // want `"Complex" can be replaced by constant\.Complex\.String\(\)`
	_ = "Float"   // want `"Float" can be replaced by constant\.Float\.String\(\)`
	_ = "Int"     // want `"Int" can be replaced by constant\.Int\.String\(\)`
	_ = "String"  // want `"String" can be replaced by constant\.String\.String\(\)`
)

const (
	_ = "Bool"    // want `"Bool" can be replaced by constant\.Bool\.String\(\)`
	_ = "Complex" // want `"Complex" can be replaced by constant\.Complex\.String\(\)`
	_ = "Float"   // want `"Float" can be replaced by constant\.Float\.String\(\)`
	_ = "Int"     // want `"Int" can be replaced by constant\.Int\.String\(\)`
	_ = "String"  // want `"String" can be replaced by constant\.String\.String\(\)`
)

var (
	_ = func(s string) string { return s }("Bool")    // want `"Bool" can be replaced by constant\.Bool\.String\(\)`
	_ = func(s string) string { return s }("Complex") // want `"Complex" can be replaced by constant\.Complex\.String\(\)`
	_ = func(s string) string { return s }("Float")   // want `"Float" can be replaced by constant\.Float\.String\(\)`
	_ = func(s string) string { return s }("Int")     // want `"Int" can be replaced by constant\.Int\.String\(\)`
	_ = func(s string) string { return s }("String")  // want `"String" can be replaced by constant\.String\.String\(\)`
)
