// Code generated by usestdlibvars, DO NOT EDIT.

package syslog_test

import "log/syslog"

var (
	_ = 1
	_ = 128
	_ = 136
	_ = 144
	_ = 152
	_ = 16
	_ = 160
	_ = 168
	_ = 176
	_ = 184
	_ = 2
	_ = 24
	_ = 3
	_ = 32
	_ = 4
	_ = 40
	_ = 48
	_ = 5
	_ = 56
	_ = 6
	_ = 64
	_ = 7
	_ = 72
	_ = 8
	_ = 80
	_ = 88
)

var (
	_, _ = syslog.New(1, "")   // want `"1" can be replaced by syslog\.LOG_ALERT`
	_, _ = syslog.New(128, "") // want `"128" can be replaced by syslog\.LOG_LOCAL0`
	_, _ = syslog.New(136, "") // want `"136" can be replaced by syslog\.LOG_LOCAL1`
	_, _ = syslog.New(144, "") // want `"144" can be replaced by syslog\.LOG_LOCAL2`
	_, _ = syslog.New(152, "") // want `"152" can be replaced by syslog\.LOG_LOCAL3`
	_, _ = syslog.New(16, "")  // want `"16" can be replaced by syslog\.LOG_MAIL`
	_, _ = syslog.New(160, "") // want `"160" can be replaced by syslog\.LOG_LOCAL4`
	_, _ = syslog.New(168, "") // want `"168" can be replaced by syslog\.LOG_LOCAL5`
	_, _ = syslog.New(176, "") // want `"176" can be replaced by syslog\.LOG_LOCAL6`
	_, _ = syslog.New(184, "") // want `"184" can be replaced by syslog\.LOG_LOCAL7`
	_, _ = syslog.New(2, "")   // want `"2" can be replaced by syslog\.LOG_CRIT`
	_, _ = syslog.New(24, "")  // want `"24" can be replaced by syslog\.LOG_DAEMON`
	_, _ = syslog.New(3, "")   // want `"3" can be replaced by syslog\.LOG_ERR`
	_, _ = syslog.New(32, "")  // want `"32" can be replaced by syslog\.LOG_AUTH`
	_, _ = syslog.New(4, "")   // want `"4" can be replaced by syslog\.LOG_WARNING`
	_, _ = syslog.New(40, "")  // want `"40" can be replaced by syslog\.LOG_SYSLOG`
	_, _ = syslog.New(48, "")  // want `"48" can be replaced by syslog\.LOG_LPR`
	_, _ = syslog.New(5, "")   // want `"5" can be replaced by syslog\.LOG_NOTICE`
	_, _ = syslog.New(56, "")  // want `"56" can be replaced by syslog\.LOG_NEWS`
	_, _ = syslog.New(6, "")   // want `"6" can be replaced by syslog\.LOG_INFO`
	_, _ = syslog.New(64, "")  // want `"64" can be replaced by syslog\.LOG_UUCP`
	_, _ = syslog.New(7, "")   // want `"7" can be replaced by syslog\.LOG_DEBUG`
	_, _ = syslog.New(72, "")  // want `"72" can be replaced by syslog\.LOG_CRON`
	_, _ = syslog.New(8, "")   // want `"8" can be replaced by syslog\.LOG_USER`
	_, _ = syslog.New(80, "")  // want `"80" can be replaced by syslog\.LOG_AUTHPRIV`
	_, _ = syslog.New(88, "")  // want `"88" can be replaced by syslog\.LOG_FTP`
)

var (
	_, _ = syslog.Dial("", "", 1, "")   // want `"1" can be replaced by syslog\.LOG_ALERT`
	_, _ = syslog.Dial("", "", 128, "") // want `"128" can be replaced by syslog\.LOG_LOCAL0`
	_, _ = syslog.Dial("", "", 136, "") // want `"136" can be replaced by syslog\.LOG_LOCAL1`
	_, _ = syslog.Dial("", "", 144, "") // want `"144" can be replaced by syslog\.LOG_LOCAL2`
	_, _ = syslog.Dial("", "", 152, "") // want `"152" can be replaced by syslog\.LOG_LOCAL3`
	_, _ = syslog.Dial("", "", 16, "")  // want `"16" can be replaced by syslog\.LOG_MAIL`
	_, _ = syslog.Dial("", "", 160, "") // want `"160" can be replaced by syslog\.LOG_LOCAL4`
	_, _ = syslog.Dial("", "", 168, "") // want `"168" can be replaced by syslog\.LOG_LOCAL5`
	_, _ = syslog.Dial("", "", 176, "") // want `"176" can be replaced by syslog\.LOG_LOCAL6`
	_, _ = syslog.Dial("", "", 184, "") // want `"184" can be replaced by syslog\.LOG_LOCAL7`
	_, _ = syslog.Dial("", "", 2, "")   // want `"2" can be replaced by syslog\.LOG_CRIT`
	_, _ = syslog.Dial("", "", 24, "")  // want `"24" can be replaced by syslog\.LOG_DAEMON`
	_, _ = syslog.Dial("", "", 3, "")   // want `"3" can be replaced by syslog\.LOG_ERR`
	_, _ = syslog.Dial("", "", 32, "")  // want `"32" can be replaced by syslog\.LOG_AUTH`
	_, _ = syslog.Dial("", "", 4, "")   // want `"4" can be replaced by syslog\.LOG_WARNING`
	_, _ = syslog.Dial("", "", 40, "")  // want `"40" can be replaced by syslog\.LOG_SYSLOG`
	_, _ = syslog.Dial("", "", 48, "")  // want `"48" can be replaced by syslog\.LOG_LPR`
	_, _ = syslog.Dial("", "", 5, "")   // want `"5" can be replaced by syslog\.LOG_NOTICE`
	_, _ = syslog.Dial("", "", 56, "")  // want `"56" can be replaced by syslog\.LOG_NEWS`
	_, _ = syslog.Dial("", "", 6, "")   // want `"6" can be replaced by syslog\.LOG_INFO`
	_, _ = syslog.Dial("", "", 64, "")  // want `"64" can be replaced by syslog\.LOG_UUCP`
	_, _ = syslog.Dial("", "", 7, "")   // want `"7" can be replaced by syslog\.LOG_DEBUG`
	_, _ = syslog.Dial("", "", 72, "")  // want `"72" can be replaced by syslog\.LOG_CRON`
	_, _ = syslog.Dial("", "", 8, "")   // want `"8" can be replaced by syslog\.LOG_USER`
	_, _ = syslog.Dial("", "", 80, "")  // want `"80" can be replaced by syslog\.LOG_AUTHPRIV`
	_, _ = syslog.Dial("", "", 88, "")  // want `"88" can be replaced by syslog\.LOG_FTP`
)

var (
	_, _ = syslog.NewLogger(1, 0)   // want `"1" can be replaced by syslog\.LOG_ALERT`
	_, _ = syslog.NewLogger(128, 0) // want `"128" can be replaced by syslog\.LOG_LOCAL0`
	_, _ = syslog.NewLogger(136, 0) // want `"136" can be replaced by syslog\.LOG_LOCAL1`
	_, _ = syslog.NewLogger(144, 0) // want `"144" can be replaced by syslog\.LOG_LOCAL2`
	_, _ = syslog.NewLogger(152, 0) // want `"152" can be replaced by syslog\.LOG_LOCAL3`
	_, _ = syslog.NewLogger(16, 0)  // want `"16" can be replaced by syslog\.LOG_MAIL`
	_, _ = syslog.NewLogger(160, 0) // want `"160" can be replaced by syslog\.LOG_LOCAL4`
	_, _ = syslog.NewLogger(168, 0) // want `"168" can be replaced by syslog\.LOG_LOCAL5`
	_, _ = syslog.NewLogger(176, 0) // want `"176" can be replaced by syslog\.LOG_LOCAL6`
	_, _ = syslog.NewLogger(184, 0) // want `"184" can be replaced by syslog\.LOG_LOCAL7`
	_, _ = syslog.NewLogger(2, 0)   // want `"2" can be replaced by syslog\.LOG_CRIT`
	_, _ = syslog.NewLogger(24, 0)  // want `"24" can be replaced by syslog\.LOG_DAEMON`
	_, _ = syslog.NewLogger(3, 0)   // want `"3" can be replaced by syslog\.LOG_ERR`
	_, _ = syslog.NewLogger(32, 0)  // want `"32" can be replaced by syslog\.LOG_AUTH`
	_, _ = syslog.NewLogger(4, 0)   // want `"4" can be replaced by syslog\.LOG_WARNING`
	_, _ = syslog.NewLogger(40, 0)  // want `"40" can be replaced by syslog\.LOG_SYSLOG`
	_, _ = syslog.NewLogger(48, 0)  // want `"48" can be replaced by syslog\.LOG_LPR`
	_, _ = syslog.NewLogger(5, 0)   // want `"5" can be replaced by syslog\.LOG_NOTICE`
	_, _ = syslog.NewLogger(56, 0)  // want `"56" can be replaced by syslog\.LOG_NEWS`
	_, _ = syslog.NewLogger(6, 0)   // want `"6" can be replaced by syslog\.LOG_INFO`
	_, _ = syslog.NewLogger(64, 0)  // want `"64" can be replaced by syslog\.LOG_UUCP`
	_, _ = syslog.NewLogger(7, 0)   // want `"7" can be replaced by syslog\.LOG_DEBUG`
	_, _ = syslog.NewLogger(72, 0)  // want `"72" can be replaced by syslog\.LOG_CRON`
	_, _ = syslog.NewLogger(8, 0)   // want `"8" can be replaced by syslog\.LOG_USER`
	_, _ = syslog.NewLogger(80, 0)  // want `"80" can be replaced by syslog\.LOG_AUTHPRIV`
	_, _ = syslog.NewLogger(88, 0)  // want `"88" can be replaced by syslog\.LOG_FTP`
)
